### ISSUE TITLE
How do i do customisation of Servertable header in react strap table?

### ISSUE THREAD

**Issue by anjaligupta140492** [AsemAlalami/react-strap-table#3]
I have to add input box, and sorting icons. But I am not able to figure out about customization part?

**Comment by AsemAlalami** [comment]
@anjaligupta140492 

Thanks for trying the library

I regret the late reply

What is the customization that you want?

customization on component style or you want to add a new component?

**Comment by AsemAlalami** [comment]
@anjaligupta140492  closed for no response
