### ISSUE TITLE
href="#" in pagination redirects to home page

### ISSUE THREAD

**Issue by KaplunYuriu** [AsemAlalami/react-strap-table#4]
Whenever I click on a pagination button, it redirects me to home screen.

**Comment by AsemAlalami** [comment]
@KaplunYuriu 

Thanks for using the library

I fixed the problem, and I added a new prop for updating the URL page

`updateUrl`: this prop to show the request parameters in URL page

```javascript
<ServerTable columns={columns} url={url} options={options} updateUrl/>
```

**Comment by KaplunYuriu** [comment]
Wonderful! Thank you!
